version: 2.1

jobs:
  do-nothing:
    docker:
      - image: "cimg/base:stable"
    steps:
      - run: echo "master branch is only for site generation"
      - run: echo "please checkout dev branch for active development"

workflows:
  empty-workflow:
    jobs:
      - do-nothing
