version: 2.1

orbs:
  node: circleci/node@4.0.0

commands:
  download-dependencies:
    steps:
      - node/install
      - run: node --version
      - run: npm install -g gatsby-cli

jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - download-dependencies
      - run: npm install
      - run: gatsby build
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - download-dependencies
      - run: npm run deploy_from_ci

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - dev
