version: 2.1

orbs:
  welcome: circleci/node@4.0.0

commands:
  download-dependencies:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - run: node --version
      - run: npm install -g gatsby-cli

jobs:
  build:
    steps:
      - checkout
      - download-dependencies
      - run: npm install

workflows:
  build-and-deploy:
    jobs:
      - build
